apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-access-check
  labels:
    app: kafka-access-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-access-check
  template:
    metadata:
      labels:
        app: kafka-access-check
    spec:
      containers:
        - name: app
          image: ghcr.io/immxmmi/puzzle-kafka-access-check:latest
          pullPolicy: Always
          ports:
            - containerPort: 2112
          livenessProbe:
            httpGet:
              path: /metrics
              port: 2112
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /metrics
              port: 2112
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: KAFKA_BOOTSTRAP
              value: "my-cluster-kafka-bootstrap.kafka:9093"
            - name: KAFKA_USERNAME
              value: "readonly-user"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: readonly-user
                  key: password
            - name: KAFKA_TOPIC
              value: "test-topic"