apiVersion: v1
kind: Service
metadata:
  name: kafka-access-check
  labels:
    app: kafka-access-check
spec:
  selector:
    app: kafka-access-check
  ports:
    - port: 80
      targetPort: 2112
      protocol: TCP
      name: http