{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default "system" }}-consumer-svc
  labels:
    app: {{ .Values.nameOverride | default "system" }}-consumer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.nameOverride | default "system" }}-consumer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- end }}