{{- if .Values.externalSecret.registry }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shared-registry-pull-secret
  labels:
    app.kubernetes.io/name: registry-pull-secret
    app.kubernetes.io/component: shared
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    creationPolicy: Owner
    name: registry-pull-secret
    template:
      data:
        .dockerconfigjson: "{{ `{{ .dcgf }}` }}"
      type: kubernetes.io/dockerconfigjson
  data:
    - remoteRef:
        key: pitc-cicd/kafka-poc/registry
        property: docker-config
      secretKey: dcgf
{{- end }}