apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-topic-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/strimzi/strimzi-kafka-operator
    path: install/topic-operator
    targetRevision: 0.46.1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true