apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "system" .Values.nameOverride }}-mqtt-producer-deployment
  labels:
    app: {{ default "system" .Values.nameOverride }}-mqtt-producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ default "system" .Values.nameOverride }}-mqtt-producer
  template:
    metadata:
      labels:
        app: {{ default "system" .Values.nameOverride }}-mqtt-producer
    spec:
      {{- with .Values.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: {{ default "system" .Values.nameOverride }}-mqtt-producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: MQTT_BROKER
              value: "{{ .Values.mqttBroker.name }}.{{ .Values.mqttBroker.namespace }}.svc.cluster.local:{{ .Values.mqttBroker.mqttPort }}"
            - name: MQTT_TOPIC
              value: {{ .Values.mqttBroker.topic }}
            - name: FETCH_INTERVAL
              value: "{{ .Values.env.FETCH_INTERVAL }}"
            - name: WEATHER_API_URL
              value: "{{ .Values.env.WEATHER_API_URL }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}