{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default "system" .Values.nameOverride }}-mqtt-producer-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ default "system" .Values.nameOverride }}-mqtt-producer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}