apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: showcase
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/immxmmi/showcase
    chart: showcase
    targetRevision: 1.0.2
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/immxmmi/kafka/main/cd/deployments/showcase/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-showcase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
