apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: showcase
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/resources
spec:
  project: default
  source:
    repoURL: ghcr.io/immxmmi/showcase
    chart: showcase
    targetRevision: 1.0.1 
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-showcase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
