apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mykafka-cluster  # Name of the Kafka cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topics.enable: false  # Prevent automatic topic creation (recommended for production)
      default.replication.factor: 2 # Default replication factor for new topics
      delete.topic.enable: true  # Disable topic deletion to prevent accidental data loss
      min.insync.replicas: 2  # Minimum number of replicas that must be in sync to acknowledge writes
      offsets.topic.replication.factor: 1  # Required for clusters with less than 3 brokers to avoid coordinator errors
      transaction.state.log.replication.factor: 1  # Ensures transaction logs can be created in small clusters
      transaction.state.log.min.isr: 1  # Minimum in-sync replicas for transaction logs in small clusters

  entityOperator:
    topicOperator: {}
    userOperator: {}