apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: writeonly-test-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operation: Write