apiVersion: v2
name:  showcase
version: 1.0.2
description: A Helm umbrella chart deploying the complete Kafka showcase stack, including Mosquitto, a Kafka system, and cluster setup.
dependencies:
  - name: mosquitto
    version: 4.8.2
    repository: oci://ghcr.io/immxmmi/mosquitto
  - name: kafka-showcase-system
    alias: solar-system
    repository: oci://ghcr.io/immxmmi/kafka-showcase-system
    version: 1.0.0
  - name: kafka-cluster-setup
    version: 1.0.0
    repository: oci://ghcr.io/immxmmi/kafka-cluster-setup