{{- if and .Values.cluster .Values.nodePool }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.cluster.version }}
    metadataVersion: {{ .Values.cluster.metadataVersion }}
    listeners:
    {{- if .Values.cluster.tlsEnabled }}
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    {{- else }}
      - name: plain
        port: 9092
        type: internal
        tls: false
    {{- end }}
    config:
{{ toYaml .Values.cluster.config | indent 6 }}

    {{- if .Values.cluster.authorization }}
    authorization:
    {{ toYaml .Values.cluster.authorization | indent 6 }}
    {{- end }}

  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}