apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/resources
spec:
  project: default
  source:
    repoURL: ghcr.io/immxmmi/kafka-cluster-setup
    chart: kafka-cluster-setup
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/immxmmi/kafka/main/cd/deployments/cluster/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
